version: '3.8'

services:
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client.run 
    ports:
      - '5173:5173'

  server:
    container_name: "server"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server.run 
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: