FROM node:18.6

WORKDIR /app

COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY package.json package.json
COPY .npmrc .npmrc
COPY ./packages/server ./packages/server
COPY ./packages/server/.env.staging ./packages/server/.env

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build:server

WORKDIR ./packages/server

EXPOSE 3000
CMD [ "pnpm", "start:prod" ]





